carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.show_cart, name='show_cart'),
    path('add_cart/<int:product_id>', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout')
]

greatkart/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('secure-login/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include ('orders.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
    path('submit-review/<int:product_id>', views.submit_review, name='submit_review')
]

carts/models.py
from django.db import models
from store.models import Product, Variation
from accounts.models import Account
# Create your models here.


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __unicode__(self):
        return self.product

store/models.py
from django.db import models
from django.urls import reverse
from django.db.models import Avg, Count
from category.models import Category
from accounts.models import Account

# Create your models here.


class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.CharField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.IntegerField()
    image = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def get_detail_url(self):
        return reverse('product_detail', kwargs={'category_slug': self.category.slug, 'product_slug': self.slug})

    def __str__(self):
        return self.product_name

    def average_review(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        if reviews['average'] is not None:
            avg = round(float(reviews['average']), 1)
            return avg
        else:
            return 0

    def count_review(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        if reviews['count'] is not None:
            count = 0
            count = int(reviews['count'])
            return count


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)


variation_category_choices = (
    ('color', 'color'),
    ('size', 'size'),
)


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choices)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject


class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/products', max_length=255)

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'

store/forms.py
from django import forms
from .models import ReviewRating


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from store.models import Product
from .models import Cart, CartItem
from store.models import Variation
from django.contrib.auth.decorators import login_required


# Create your views here.


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id)
    if current_user.is_authenticated:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]
                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key,
                                                      variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        is_cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product,
                                                user=current_user)
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variations = item.variations.all()
                ex_var_list.append(list(existing_variations))
                id.append(item.id)
            if product_variation in ex_var_list:
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(product=product, quantity=1, user=current_user)
                if len(product_variation) > 0:
                    item.variations.add(*product_variation)
                item.save()
        else:
            cart_item = CartItem.objects.create(product=product,
                                                user=current_user ,
                                                quantity=1)
            if len(product_variation) > 0:
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('show_cart')
    else:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]
                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass
        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(cart_id=_cart_id(request))
            cart.save()

        is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product,
                                                cart=cart)
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variations = item.variations.all()
                ex_var_list.append(list(existing_variations))
                id.append(item.id)
            if product_variation in ex_var_list:
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(product=product, quantity=1, cart=cart)
                if len(product_variation) > 0:
                    item.variations.add(*product_variation)
                item.save()
        else:
            cart_item = CartItem.objects.create(product=product,
                                                cart=cart,
                                                quantity=1)
            if len(product_variation) > 0:
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('show_cart')


def remove_cart(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(user = request.user, product=product, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(cart=cart, product=product, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect('show_cart')


def remove_cart_item(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(user=request.user, product=product, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(cart=cart, product=product, id=cart_item_id)
    cart_item.delete()
    return redirect('show_cart')


def show_cart(request, quantity=0, total=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2 * total) / 100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass
    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
    }
    return render(request, 'store/cart.html', context)


@login_required(login_url='login')
def checkout(request, total=0, quantity=0, cart_items=None):
    tax = 0
    grand_total = 0
    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2 * total) / 100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass
    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
    }
    return render(request, 'store/checkout.html', context)

store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product, ReviewRating, ProductGallery
from category.models import Category
from carts.models import Cart, CartItem
from carts.views import _cart_id
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from .forms import ReviewForm

# Create your views here.


def store(request, category_slug=None):
    categories = None
    products = None
    if category_slug is not None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=categories, is_available=True).order_by('-id')
        products_count = products.count()
    else:
        products = Product.objects.all().filter(is_available=True).order_by('-id')
        products_count = products.count()
    paginator = Paginator(products, 6)
    page = request.GET.get('page')
    paginated_products = paginator.get_page(page)

    context = {
        'products': paginated_products,
        'products_count': products_count,

    }
    return render(request, 'store/store.html', context)


def product_detail(request, category_slug, product_slug):
    try:
        single_object = Product.objects.get(category__slug=category_slug, slug=product_slug)
        in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(request), product=single_object).exists()
    except Exception as e:
        raise e

    reviews = ReviewRating.objects.filter(product_id=single_object.id, status=True).order_by('-updated_date')

    product_gallery = ProductGallery.objects.filter(product_id=single_object.id)

    context = {
        'product': single_object,
        'in_cart': in_cart,
        'reviews': reviews,
        'product_gallery': product_gallery,
    }
    return render(request, 'store/product_detail.html', context=context)


def search(request):
    products = None
    products_count = 0
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            products = Product.objects.order_by('-created_date').filter(Q(product_name__icontains=keyword)
                                                                        | Q(description__icontains=keyword))
            products_count = products.count()
    context = {
        'products': products,
        'products_count': products_count,
    }
    return render(request, 'store/store.html', context)


def submit_review(request, product_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        try:
            reviews = ReviewRating.objects.get(user__id=request.user.id, product__id=product_id)
            form = ReviewForm(request.POST, instance=reviews)
            form.save()
            messages.success(request, 'Thank you! Your review has been updated.')
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.user_id = request.user.id
                data.save()
                messages.success(request, 'Thank you! Your review has been submitted.')
                return redirect(url)

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Cart</title>
{% endblock %}

{% block content %}
<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
{% if not cart_items %}
	<div class="text-center">
		<h3 class="text-center">Your shopping cart is empty</h3>
		<br>
		<a href="{% url 'store' %}" class="btn btn-primary">Continue shopping</a>
	</div>
{% else %}
<div class="row">
	<aside class="col-lg-9">
<div class="card">
<table class="table table-borderless table-shopping-cart">
<thead class="text-muted">
<tr class="small text-uppercase">
  <th scope="col">Product</th>
  <th scope="col" width="120">Quantity</th>
  <th scope="col" width="120">Price</th>
  <th scope="col" class="text-right" width="200"> </th>
</tr>
</thead>
<tbody>
{% for cart_item in cart_items %}
<tr>
	<td>
		<figure class="itemside align-items-center">
			<div class="aside"><img src="{{ cart_item.product.image.url }}" class="img-sm"></div>
			<figcaption class="info">
				<a href="{{ cart_item.product.get_detail_url }}" class="title text-dark">{{ cart_item.product.product_name }}</a>
				<p class="text-muted small">
					{% if cart_item.variations.all %}
						{% for item in cart_item.variations.all %}
							{{ item.variation_category | capfirst }}: {{item.variation_value | capfirst }}<br>
						{% endfor %}
					{% endif %}
				</p>
			</figcaption>
		</figure>
	</td>
	<td>
		<!-- col.// -->
					<div class="col">
						<div class="input-group input-spinner">
							<div class="input-group-prepend">
							<a href="{% url 'remove_cart' product_id=cart_item.product.id cart_item_id=cart_item.id %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
							</div>
							<input type="text" class="form-control"  value="{{ cart_item.quantity }}">
							<div class="input-group-append">
								<form action="{% url 'add_cart' product_id=cart_item.product.id %}" method="POST">
										{% csrf_token %}
										{% for item in cart_item.variations.all %}
											<input type="hidden" name="{{ item.variation_category | lower }}" value="{{ item.variation_value | capfirst }}">
										{% endfor %}
										<button class="btn btn-light" type="submit" id="button-minus"> <i class="fa fa-plus"></i> </button>
								</form>
							</div>
						</div> <!-- input-group.// -->
					</div> <!-- col.// -->
	</td>
	<td>
		<div class="price-wrap">
			<var class="price">${{ cart_item.sub_total }}</var>
			<small class="text-muted"> ${{ cart_item.product.price }} each </small>
		</div> <!-- price-wrap .// -->
	</td>
	<td class="text-right">
	<a href="{% url 'remove_cart_item' product_id=cart_item.product.id cart_item_id=cart_item.id%}" onclick="return confirm('Are you sure that you want to remove this product?')" class="btn btn-danger"> Remove</a>
	</td>
</tr>
{% endfor %}
</tbody>
</table>
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-3">

		<div class="card">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Total price:</dt>
			  <dd class="text-right">${{ total }}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Tax:</dt>
			  <dd class="text-right"> ${{ tax }}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Total:</dt>
			  <dd class="text-right text-dark b"><strong>${{ grand_total }}</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src="{% static './images/misc/payments.png' %}" height="26">
			</p>
			<a href="{% url 'checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
			<a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside> <!-- col.// -->


</div> <!-- row.// -->
	{% endif %}
<!-- ============================ COMPONENT 1 END .// ================================= -->

</div> <!-- container .//  -->
</section>

{% endblock %}

templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>{{ product.product_name }}</title>
{% endblock %}

{% block content %}
<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
<div class="card">
	<div class="row no-gutters">
		<aside class="col-md-6">
<article class="gallery-wrap">
	<div class="img-big-wrap main-image">
	   <center><img src="{{ product.image.url }}"></a></center>
	</div> <!-- img-big-wrap.// -->

</article> <!-- gallery-wrap .end// -->
			<ul class="thumb">
				<li>
					<a href="{{ product.image.url }}" target="main-image"><img src="{{ product.image.url }}" alt="Product image"> </a>
					{% for i in product_gallery %}
					<a href="{{i.image.url}}" target="main-image"><img src="{{i.image.url}}" alt="Product image"> </a>
					{% endfor %}
				</li>
			</ul>
		</aside>
		<main class="col-md-6 border-left">
			<form action="{% url 'add_cart' product_id=product.id %}" method="POST">
				{% csrf_token %}
<article class="content-body">

<h2 class="title">{{ product.product_name }}</h2>
	{% if product.average_review %}
	<div style="padding: 4px 0 8px;">
		<span class="review-stars">
			<i class="fa fa-star{% if product.average_review < 0.5 %}-o{% elif product.average_review >= 0.5 and product.average_review < 1 %}-half-o{% endif %}"></i>
			<i class="fa fa-star{% if product.average_review < 1.5 %}-o{% elif product.average_review >= 1.5 and product.average_review < 2 %}-half-o{% endif %}"></i>
			<i class="fa fa-star{% if product.average_review < 2.5 %}-o{% elif product.average_review >= 2.5 and product.average_review < 3 %}-half-o{% endif %}"></i>
			<i class="fa fa-star{% if product.average_review < 3.5 %}-o{% elif product.average_review >= 3.5 and product.average_review < 4 %}-half-o{% endif %}"></i>
			<i class="fa fa-star{% if product.average_review < 4.5 %}-o{% elif product.average_review >= 4.5 and product.average_review < 5 %}-half-o{% endif %}"></i>
		</span>
		<a href="#" id="click-review" style="padding-left:5px; font-weight:500;">{{ product.count_review }} {% if product.count_review == 1 %}review {% else %}reviews{% endif %}</a>
	</div>
	{% endif %}

<div class="mb-3">
	<var class="price h4">${{ product.price }}</var>
</div>

<p>{{ product.description }}</p>


<hr>
	<div class="row pl-2">
		<div class="item-option-select">
			<h6>Choose Color</h6>
			<select name="color" class="form-control" required>
				<option value="" selected disabled>Select</option>
				{% for i in product.variation_set.colors %}
				<option value="{{ i.variation_value | lower}}">{{ i.variation_value | capfirst}}</option>
				{% endfor %}
			</select>
		</div>
	</div> <!-- row.// -->
	<div class="row pl-2">
		<div class="item-option-select">
			<h6>Select Size</h6>
			<select name="size" class="form-control" required>
				<option value="" selected disabled>Select</option>
				{% for i in product.variation_set.sizes %}
				<option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
				{% endfor %}
			</select>
		</div>
	</div> <!-- row.// -->
	<hr>
	{% if product.stock <= 0 %}
	<h4 class="text-danger">Out of stock</h4>
	{% else %}
	<button type="submit" class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </button>
	{% endif %}
</article> <!-- product-info-aside .// -->
				</form>
		</main> <!-- col.// -->
	</div> <!-- row.// -->
</div> <!-- card.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

<br>

<div class="row">
			<div class="col-md-9">

	<header class="section-heading">
		<h3 class="pl-1">Customer Reviews </h3>

	</header>
				<div style="max-width:900px;">
				{% include 'includes/alerts.html' %}
				</div>
				{% if user.is_authenticated %}
	<form action="{% url 'submit_review' product_id=product.id %}" method="POST">
    {% csrf_token %}
		<h5 class="pl-1">Write your review</h5>
		<div>
			<label class="pl-1 pt-1">How do you rate this product?</label>
			<br>
			<div class="rate" style="padding:2px 0;">
				<input type="radio" name="rating" id="rating10" value="5" required> <label for="rating10" title="5"></label>
				<input type="radio" name="rating" id="rating9" value="4.5" required> <label for="rating9" title="4.5" class="half"></label>
				<input type="radio" name="rating" id="rating8" value="4" required> <label for="rating8" title="4"></label>
				<input type="radio" name="rating" id="rating7" value="3.5" required> <label for="rating7" title="3.5" class="half"></label>
				<input type="radio" name="rating" id="rating6" value="3" required> <label for="rating6" title="3"></label>
				<input type="radio" name="rating" id="rating5" value="2.5" required> <label for="rating5" title="2.5" class="half"></label>
				<input type="radio" name="rating" id="rating4" value="2" required> <label for="rating4" title="2"></label>
				<input type="radio" name="rating" id="rating3" value="1.5" required> <label for="rating3" title="1.5" class="half"></label>
				<input type="radio" name="rating" id="rating2" value="1" required> <label for="rating2" title="1"></label>
				<input type="radio" name="rating" id="rating1" value="0.5" required> <label for="rating1" title="0.5" class="half"></label>
			</div>
			<br>
			<h6 class="pl-1">Review Title:</h6>
			<input type="text" class="form-control" name="subject">
			<br>
			<h6 class="pl-1">Review</h6>
			<textarea name="review" rows="4" class="form-control"></textarea>
			<br>
			<input class='btn btn-primary' type="submit" value="Submit Review">
		</div>
	</form>
				{% else %}
				<p class="pl-2" style="font-size:1.1rem;;">You have to <span><a href="{% url 'login' %}">login</a></span> to post a review</p>
				{% endif %}
	<br>
				<div id="start-reviews"></div>
				{% for review in reviews %}
	<article class="box mb-3">

		<div class="icontext w-100">
			{% if review.user.userprofile.profile_picture %}
			<img src="{{ review.user.userprofile.profile_picture.url }}" class="img-xs icon rounded-circle">
			{% else %}
			<img src="{% static './images/avatars/default.png' %}" class="img-xs icon rounded-circle">
			{% endif %}
			<div class="text">
				<span class="date text-muted float-md-right">{{ review.updated_date }} </span>
				<h6 class="mb-1">{{ review.user.full_name }} </h6>
				<div class="review-stars">
					<i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
					<i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
					<i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
					<i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
					<i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>

					</div>

			</div>
		</div> <!-- icontext.// -->
		<div class="mt-3">
			<h6>{{ review.subject }}</h6>
			<p>
				{{ review.review }}
			</p>
		</div>

			</article>
				{% endfor %}



	</div> <!-- col.// -->
</div> <!-- row.// -->


</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
	        $(document).ready(function (){
            $("#click-review").click(function (){
                $('html, body').animate({
                    scrollTop: $("#start-reviews").offset().top
                }, 1000);
            });
        });
</script>

<script>
	$(document).ready(function(){
		$('.thumb a').click(function(e){
			e.preventDefault();
			$('.main-image img').attr('src', $(this).attr("href"));
		})
	})
</script>

{% endblock %}